# Generated by Django 3.2.16 on 2024-04-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240421_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(null=True, verbose_name='Комментарии'),
        ),
    ]
