# Generated by Django 3.2.16 on 2024-04-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
